services:
  app:
    build: .
    container_name: SUDuyuru-container
    command: python3 ./src/main.py
    ports:
      - 5678:5678
    volumes:
      - .:/code
    depends_on:
      - mongo
  
  mongo:
    image: mongo:6.0.13-jammy
    container_name: SUDuyuru-mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: Duyurular
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./data/db/mongo_init.js:/docker-entrypoint-initdb.d/mongo_init.js:ro
