services:
  app:
    build: .
    container_name: SUDuyuru-container
    command: python3 ./src/main.py
    ports:
      - 5678:5678
    volumes:
      - .:/code
    depends_on:
      - mongo
  
  mongo:
    image: mongo:6.0.13-jammy
    container_name: SUDuyuru-mongo
    ports:
      - 27017:27017
    volumes:
      - .:/data/db
